# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uusTU7E2IoLm8E5BmRdoof2HRIvQtep
"""

for i in range(1,5):
  for j in range(i,4):
    print(" ",end="")
  for k in range(1,i+1):
    print("*",end=" ")
  print("")

for i in range(4,0,-1):
  for j in range(4,i-1,-1):
    print(" ",end="")
  for k in range(1,i+1):
    print("*",end=" ")
  print("")

for i in range(65,70):
  for j in range(i,69):
    print(" ",end="")
  for k in range(65,i+1):
    print(chr(k),end=" ")
  print("")

for i in range(1,6):
  for j in range(1,i+1):
    if(j==1 or j==i or i==5):
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print("")

for i in range(1,6):
  for j in range(i,5):
    print(" ",end="")
  for k in range(1,i+1):
    if (k==1 or k==i or i==5):
      print(k,end=" ")
    else:
      print(" ",end=" ")
  print("")

# list datatype
# collection of element
# stored based on index position
# sequence datatype


x=[10,20,30,40,50,"hey",100.0]
print(type(x))

x=[10,20,30,40,50,"hey",100.0]
print(x[0:4])

x=[10,20,30,40,50,"hey",100.0]
x[0]=90  # update
print(x)

x=[10,20,30,40,50,"hey",100.0]
x.append(100)
print(x)

x=[10,20,30,40,50,"hey",100.0]
x.extend("Hello")
print(x)

x=[10,20,30,40,50,"hey",100.0]
x.extend("Hello")
x.extend([999,'hello'])
print(x)

x=[10,20,30,40,50,"hey",100.0]
x.remove(10)
print(x)

x=[10,20,30,40,50,"hey",100.0]
for i in range(0,len(x)):
  print(i,x[i])

